class DropTablesUnused < ActiveRecord::Migration[5.2]
  def change
    drop_table :agreement_statuses
    drop_table :agreement_types
    drop_table :arp_roles
    drop_table :agreements
    drop_table :arp_assignment_reports
    drop_table :agreements_group_members
    drop_table :agreements_research_groups
    drop_table :arp_assignments
    drop_table :arp_act_s_goals
    drop_table :arp_activities
    drop_table :arp_activity_reports
    drop_table :agreement_research_projects
    drop_table :arp_expenses
    drop_table :arp_general_goals
    drop_table :arp_members
    drop_table :arp_payments
    drop_table :arp_specific_goals
    drop_table :call_item_categories
    drop_table :calls_required_documents
    drop_table :call_user_roles
    drop_table :call_types
    drop_table :calls_product_types
    drop_table :contribution_funding_entity_items
    drop_table :contribution_rp_items
    drop_table :contributions
    drop_table :document_types
    drop_table :entity_types
    drop_table :fe_contacts
    drop_table :funding_entities
    drop_table :genres
    drop_table :duration_types
    drop_table :institutions
    drop_table :required_types
    drop_table :required_documents
    drop_table :plan_periods
    drop_table :item_categories
    drop_table :research_project_plans
    drop_table :research_seedbeds
    drop_table :researcher_formation_plans
    drop_table :researcher_types
    drop_table :result_transfer_plans
    drop_table :seedbed_members
    drop_table :sm_periods
    drop_table :snies
    drop_table :state_seedbeds
    drop_table :calls
    drop_table :social_appropriation_plans
  end
end
